#!/bin/bash

server=10.253.0.13
windowsclient=10.253.0.14

myscript=$(basename $0)
if [ ! -f "$myscript" ] ; then
	echo "Please run $myscript whilst standing in the same directory" 1>&2
	exit 1
fi

path="$PWD"
build="$path/build"
target="$path/target"

fail()
{
	echo
	echo "Test setup failed: $@"
	echo
	exit 1
}

makedir()
{
	rm -rf "$1"
	mkdir -p "$1" || fail "could not mkdir $1"
}

cdir()
{
	cd "$1" || fail "could not cd to $1"
}

build_and_install()
{
	# Create a build directory, and fill it with the source.
	makedir "$build"
	makedir "$build/test"
	ls ../ | while read f ; do
		[ "$f" = "test" ] && continue
		[ "$f" = ".git" ] && continue
		cp -ar ../"$f" "$build" || fail "could not copy ../$f to $build"
	done || exit 1

	# Create a target directory, compile burp and install it into the
	# target.
	makedir "$target"
	cdir "$build"
	make clean
	./configure || fail "configure failed"
	make || fail "make failed"
	# For some reason, make is not returning an error code.
	# Look for important binaries before carrying on.
	[ -f src/burp ] || fail "make failed"
	[ -f src/bedup ] || fail "make failed"
	make install DESTDIR="$target" || fail "make install failed"
	cdir -

	# Now build the Windows installer.
	cdir "$build/src/win32"
	make WIN64=yes || fail

	# Now copy the Windows installer to the client
	installer=$(find -name burp-win64-installer*.exe)
	[ -z "$windowsclient" ] && fail
	scp "$installer" "$windowsclient:" || fail

	# Remove any previous installation.
	ssh "$windowsclient" rm -rf \'/cygdrive/c/Program Files/Burp\' || fail

	# Now run the Windows installer
	installer=$(basename $installer)
	ssh "$windowsclient" ./$installer /S || fail

	cdir -
}

build_and_install

# Copy the build directory to the client, to give it something to backup.
cdir "$path" || fail
tar -cjf build.tar.bz2 build || fail
scp build.tar.bz2 "$windowsclient:" || fail
clientburpdir="/cygdrive/c/Program Files/Burp"
ssh "$windowsclient" tar -xjf build.tar.bz2 -C \'$clientburpdir\' || fail

# args:
# 1 - directory where build was installed
# 2 - location of client burp
# 3 - location of client conf (for editing)
# 4 - location of client conf (for giving as option to burp binary)
# 5 - directory to backup
# 6 - directory to restore to
# 7 - address of the server
# 8 - ssh command (leave unset for self test)
./test_main \
	"$target" \
	\'"$clientburpdir/bin/burp.exe"\' \
	\'"$clientburpdir/burp.conf"\' \
	\'"C:\Program Files\Burp\burp.conf"\' \
	\'"$clientburpdir/build"\' \
	\'"$clientburpdir/restore"\' \
	"$server" \
	"ssh $windowsclient"

exit 0
