#!/bin/sh

if [ -z "$1" -o -z "$2" -o -z "$3" ] ; then
	echo "Not enough arguments" 1>&2
	exit 1
fi

(echo "To: $2"
 echo "From: burp"
 echo "Subject: $3"
 /usr/sbin/burp -c "$1" -a S
 echo) | /usr/sbin/sendmail -t
