#!/bin/sh
#

NM=../../../../cross-tools/mingw32/mingw32/bin/nm
 
echo "LIBRARY burp.dll"
echo "EXPORTS"
echo " "

for i in *.o ; do \
   echo "; $i"; \
   ${NM} $i | grep "^[0-9a-f]* T _" | cut -c13- ; \
   echo " "; \
done

DATA="\
   console_command \
   plugin_list"

for i in ${DATA}; do \
   echo "$i DATA"; \
done
