#!/bin/bash

destdir="$1"
sysconfdir="$2"
sbindir="$3"

usage()
{
	echo "usage: $0 <destdir> <sysconfdir> <sbindir>" 1>&2
	exit 1
}

[ -z "$sysconfdir" ] && usage
[ -z "$sbindir" ] && usage

safe_cp()
{
	src="$1"
	dst="$destdir/$2"
	[ -f "$dst" ] && return 1
	cp "$src" "$dst"
	return 0
}

safe_cp_and_chmod()
{
	safe_cp "$1" "$2" && chmod 755 "$destdir/$2"
}

cp_and_chmod()
{
	src="$1"
	dst="$destdir/$2"
	cp "$1" "$dst" && chmod 755 "$destdir/$2"
}

safe_cp configs/client/burp.conf		"$sysconfdir"/burp.conf
safe_cp configs/server/burp.conf		"$sysconfdir"/burp-server.conf
safe_cp configs/server/clientconfdir/incexc	"$sysconfdir"/clientconfdir/incexc/example 
safe_cp configs/server/clientconfdir/testclient	"$sysconfdir"/clientconfdir/testclient 
safe_cp configs/server/clientconfdir/incexc	"$sysconfdir"/clientconfdir/incexc/example
safe_cp configs/server/autoupgrade/windows.script "$sysconfdir"/autoupgrade/server/win32/script
safe_cp configs/server/autoupgrade/windows.script "$sysconfdir"/autoupgrade/server/win64/script

safe_cp_and_chmod configs/server/notify_script	"$sysconfdir"/notify_script
safe_cp_and_chmod configs/server/summary_script	"$sysconfdir"/summary_script
safe_cp_and_chmod configs/server/timer_script	"$sysconfdir"/timer_script
safe_cp_and_chmod configs/server/ssl_extra_checks_script "$sysconfdir"/ssl_extra_checks_script
safe_cp configs/certs/CA/CA.cnf			"$sysconfdir"/CA.cnf

cp_and_chmod configs/certs/CA/burp_ca		"$sbindir"/burp_ca
